[tool.ruff]
line-length = 120
lint.select = [
    'W',
    'ARG',
    'ANN',
    'ASYNC',
    'B',
    'COM',
    'C4',
    'C90',
    'DTZ',
    'E',
    'ERA',
    'F',
    'UP',
    'T10',
    'T20',
    'Q',
    'S',
    'I',
    'N',
    'YTT',
    'PTH',
]

lint.exclude = [
    '.git',
    '.mypy_cache',
    '.ruff_cache',
    '__pycache__',
    'manage.py',
    '*/migrations/*',
]

lint.fixable = ["ALL"]

# Allow unused variables when underscore-prefixed.
lint.dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

target-version = "py311"

[tool.ruff.lint.mccabe]
max-complexity = 4